// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6dnf7eFWdJQHT1g4w0Oeyqt6eyAc4EKI',
    appId: '1:278601799608:web:4cf95dbde786508ab0e14d',
    messagingSenderId: '278601799608',
    projectId: 'booknstay-d9210',
    authDomain: 'booknstay-d9210.firebaseapp.com',
    storageBucket: 'booknstay-d9210.firebasestorage.app',
    measurementId: 'G-B0929KDX8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC0eR428HSCzT4onA-lAVFUZf64Yw6_vY',
    appId: '1:278601799608:android:731d046f328a1927b0e14d',
    messagingSenderId: '278601799608',
    projectId: 'booknstay-d9210',
    storageBucket: 'booknstay-d9210.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCGJU48_Pm3a2BYERV-nJ4nHi7Tz1KCLs',
    appId: '1:278601799608:ios:b954ecb2049a6031b0e14d',
    messagingSenderId: '278601799608',
    projectId: 'booknstay-d9210',
    storageBucket: 'booknstay-d9210.firebasestorage.app',
    iosBundleId: 'com.example.bookNStay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCGJU48_Pm3a2BYERV-nJ4nHi7Tz1KCLs',
    appId: '1:278601799608:ios:b954ecb2049a6031b0e14d',
    messagingSenderId: '278601799608',
    projectId: 'booknstay-d9210',
    storageBucket: 'booknstay-d9210.firebasestorage.app',
    iosBundleId: 'com.example.bookNStay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6dnf7eFWdJQHT1g4w0Oeyqt6eyAc4EKI',
    appId: '1:278601799608:web:c8dda1e486d27c5bb0e14d',
    messagingSenderId: '278601799608',
    projectId: 'booknstay-d9210',
    authDomain: 'booknstay-d9210.firebaseapp.com',
    storageBucket: 'booknstay-d9210.firebasestorage.app',
    measurementId: 'G-JG2996JJNC',
  );
}
